version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ogps_reports_db
      POSTGRES_USER: ogpsuser
      POSTGRES_PASSWORD: ogpspass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./OGPS-REPORTS/OGPS_REPORTS_db/PersonOGPS.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./OGPS-REPORTS
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ogps_reports_db
      SPRING_DATASOURCE_USERNAME: ogpsuser
      SPRING_DATASOURCE_PASSWORD: ogpspass

  frontend:
    build:
      context: ./ogps-reports-frontend/ogps-reports-frontend
      dockerfile: ../Dockerfile
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  pgdata:
